Removing the character '&' from config.xml
I change '&' with 'and' because that character may creates problems while parsing the config.xml

In my Ionic2 project I had to remove ios and put it back.
But I couldn't do it because of this error:

`Error parsing /Applications/my_project/alpha7/plugins/cordova-plugin-nativeaudio/plugin.xml.
Error: Invalid character in entity name
Line: 8
Column: 54`

After changing '&' with 'and' everything worked out fine.